{
 "title": "DEVWKS-2594 4-node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Raw Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "nx-os9000v-1",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ip_prefix_path_traffic{instance=\"nx-osv9000-1:8888\",family=\"unicast\"}"
      }
     ]
    },
    {
     "title": "nx-os9000v-2",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ip_prefix_path_traffic{instance=\"nx-osv9000-2:8888\",family=\"unicast\"}"
      }
     ]
    },
    {
     "title": "nx-os9000v-3",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ip_prefix_path_traffic{instance=\"nx-osv9000-3:8888\",family=\"unicast\"}"
      }
     ]
    },
    {
     "title": "nx-os9000v-4",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ip_prefix_path_traffic{instance=\"nx-osv9000-4:8888\",family=\"unicast\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "nx-os9000v-1",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ip_prefix_path_traffic{instance=\"nx-osv9000-1:8888\",family=\"unicast\"}[5m])"
      }
     ]
    },
    {
     "title": "nx-os9000v-2",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ip_prefix_path_traffic{instance=\"nx-osv9000-2:8888\",family=\"unicast\"}[5m])"
      }
     ]
    },
    {
     "title": "nx-os9000v-3",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ip_prefix_path_traffic{instance=\"nx-osv9000-3:8888\",family=\"unicast\"}[5m])"
      }
     ]
    },
    {
     "title": "nx-os9000-4",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ip_prefix_path_traffic{instance=\"nx-osv9000-4:8888\",family=\"unicast\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Changes in Routes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "nx-os9000v-1",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(ip_prefix_path_count{instance=\"nx-osv9000-1:8888\",vrf=\"default\"}[30s])"
      }
     ]
    }
   ]
  }
 ]
}