# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "nexus9300v/9.3.3"
  config.vm.boot_timeout = 600
  config.ssh.shell = "run bash"
  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 23456

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--uart1", "0x3f8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "tcpserver", "2023"]
  end

end
